### ISSUE TITLE
Requesting Login.html

### ISSUE THREAD

**Issue by epicseven-cup** [Ai-Jesse/Blue-Jesse#5]
**A html page for user to login**
A login page with a login box that has the input of username, and password and a login and signup button 

**Describe the solution you'd like**
N/A feel free to anything

**Additional context**
![image](https://user-images.githubusercontent.com/59263116/198915147-b42421a7-59ff-455e-8dbd-cd3c7dbdc5a2.png)

**Comment by nishtha53** [comment]
can i work on this issue?

**Comment by epicseven-cup** [comment]
> can i work on this issue?

Sorry this is a class project no outside contribution allow sorry

**Comment by nishtha53** [comment]
@epicseven-cup oh okay I m sorry

**Comment by epicseven-cup** [comment]
> @epicseven-cup oh okay I m sorry

No need that is my fault to not mention it sorry about that

**Comment by epicseven-cup** [comment]
issue complete with redirecting
